//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDataModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_MKT_PortfolioBase
    {
        public string StockId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<double> ExcessiveReturn1 { get; set; }
        public Nullable<double> ExcessiveReturn2 { get; set; }
        public Nullable<double> ResidentialReturn1 { get; set; }
        public Nullable<double> ResidentialReturn2 { get; set; }
        public Nullable<double> ExcessiveReturnRisk { get; set; }
        public Nullable<double> ResidentialReturnRisk { get; set; }
        public Nullable<double> ExcessiveReturnSharpeRatio { get; set; }
        public Nullable<double> ResidentialReturnSharpeRatio { get; set; }
        public Nullable<double> Determination { get; set; }
        public string DeterminationAlgorithm { get; set; }
        public string AverageAlgorithm { get; set; }
        public System.Guid UniqueId { get; set; }
        public Nullable<double> AverageVolatilityToDate { get; set; }
        public Nullable<double> AverageNonSysRiskToDate { get; set; }
        public Nullable<double> AveragePriceInPastWeek { get; set; }
        public Nullable<double> AveragePriceInPastMonth { get; set; }
        public Nullable<double> AveragePriceInPastTwoMonth { get; set; }
        public Nullable<double> AveragePriceInPastThreeMonth { get; set; }
        public Nullable<double> AveragePriceInPastSixMonth { get; set; }
        public Nullable<double> AveragePriceInPastYear { get; set; }
    
        public virtual TRD_Co TRD_Co { get; set; }
    }
}
