//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockDataModelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRD_Co_Quarter_DevIndex
    {
        public string StockID { get; set; }
        public string DateAsOfReporting { get; set; }
        public string TypeOfReport { get; set; }
        public string IndustryID { get; set; }
        public Nullable<double> RatioCapitalHoldNRiseA { get; set; }
        public Nullable<double> C_RatioCapitalHoldNRiseB { get; set; }
        public Nullable<double> RatioCapitalHoldNRiseAttrToCompany { get; set; }
        public Nullable<double> RatioCapitalAccumulationA { get; set; }
        public Nullable<double> RatioCapitalAccumulationB { get; set; }
        public Nullable<double> RatioCapitalAccumulationAttrToCompany { get; set; }
        public Nullable<double> FixedAssetGrowthRateA { get; set; }
        public Nullable<double> FixedAssetGrowthRateB { get; set; }
        public Nullable<double> TotalAssetGrowthRateA { get; set; }
        public Nullable<double> TotalAssetGrowthRateB { get; set; }
        public Nullable<double> GrowthRateROEA { get; set; }
        public Nullable<double> GrowthRateROEB { get; set; }
        public Nullable<double> GrowthRateEPSA { get; set; }
        public Nullable<double> GrowthRateEPSB { get; set; }
        public Nullable<double> GrowthRateDiluatedEPSA { get; set; }
        public Nullable<double> GrowthRateDiluatedEPSB { get; set; }
        public Nullable<double> GrowthRateNetProfitA { get; set; }
        public Nullable<double> GrowthRateNetProfitB { get; set; }
        public Nullable<double> GrowthRateTotalProfitA { get; set; }
        public Nullable<double> C_GrowthRateTotalProfitB { get; set; }
        public Nullable<double> GrowthRateOperatingProfitA { get; set; }
        public Nullable<double> GrowthRateOperatingProfitB { get; set; }
        public Nullable<double> GrowthRateNetProfitAttrToCompany { get; set; }
        public Nullable<double> GrowthRateTotalIncome { get; set; }
        public Nullable<double> GrowthRateTotalIncomeAttrToCompany { get; set; }
        public string GrowthRateOperatingIncomeA { get; set; }
        public string C_GrowthRateOperatingIncomeC { get; set; }
        public Nullable<double> GrowthRateGrossRevenue { get; set; }
        public Nullable<double> GrowthRateTotalOperatingCost { get; set; }
        public string GrowthRateMarketingExpense { get; set; }
        public string GrowthRateMgmtExpense { get; set; }
        public Nullable<double> Accurals { get; set; }
        public Nullable<double> GrowthRateNetOACashFlowPSA { get; set; }
        public Nullable<double> GrowthRateNetOACashFlowPSB { get; set; }
        public Nullable<double> C_GrowthRateNetOACashFlowA { get; set; }
        public Nullable<double> C_GrowthRateNetOACashFlowB { get; set; }
        public Nullable<double> C_GrowthRateNetIACashFlowA { get; set; }
        public Nullable<double> C_GrowthRateNetIACashFlowB { get; set; }
        public Nullable<double> GrowthRateNetFACashFlowA { get; set; }
        public Nullable<double> GrowthRateNetFACashFlowB { get; set; }
        public Nullable<double> SustainableGrowthRate { get; set; }
        public Nullable<double> GrowthRateOwnerEquityA { get; set; }
        public Nullable<double> GrowthRateOwnerEquityB { get; set; }
        public Nullable<double> GrowthRateNetAssetValuePSA { get; set; }
        public Nullable<double> GrowthRateNetAssetValuePSB { get; set; }
        public System.Guid UniqueID { get; set; }
    }
}
